/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './app/__root'
import { Route as PageRouteImport } from './app/page'
import { Route as StatsPageRouteImport } from './app/stats/page'
import { Route as AdminPageRouteImport } from './app/admin/page'
import { Route as AboutPageRouteImport } from './app/about/page'
import { Route as ApiTasksRouteRouteImport } from './app/api/tasks/route'
import { Route as ApiStatsRouteRouteImport } from './app/api/stats/route'
import { Route as ApiCrawlRouteRouteImport } from './app/api/crawl/route'
import { Route as ApiArticlesRouteRouteImport } from './app/api/articles/route'
import { Route as TasksIdPageRouteImport } from './app/tasks/$id/page'
import { Route as ApiTasksClearFailedRouteRouteImport } from './app/api/tasks/clear-failed/route'
import { Route as ApiTasksIdRouteRouteImport } from './app/api/tasks/$id/route'
import { Route as ApiCronCheckCookieRouteRouteImport } from './app/api/cron/check-cookie/route'
import { Route as ApiAdminFeedbackRouteRouteImport } from './app/api/admin/feedback/route'
import { Route as ApiAdminCookieStatusRouteRouteImport } from './app/api/admin/cookie-status/route'
import { Route as ApiAdminConfigRouteRouteImport } from './app/api/admin/config/route'
import { Route as ApiAdminCheckCookieRouteRouteImport } from './app/api/admin/check-cookie/route'
import { Route as ApiAdminAuthRouteRouteImport } from './app/api/admin/auth/route'
import { Route as ApiAdminArticlesRouteRouteImport } from './app/api/admin/articles/route'
import { Route as ApiTasksIdFeedbackRouteRouteImport } from './app/api/tasks/$id/feedback/route'
import { Route as ApiAdminFeedbackIdRouteRouteImport } from './app/api/admin/feedback/$id/route'
import { Route as ApiAdminArticlesIdRouteRouteImport } from './app/api/admin/articles/$id/route'

const PageRoute = PageRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StatsPageRoute = StatsPageRouteImport.update({
  id: '/stats/',
  path: '/stats/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPageRoute = AdminPageRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutPageRoute = AboutPageRouteImport.update({
  id: '/about/',
  path: '/about/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTasksRouteRoute = ApiTasksRouteRouteImport.update({
  id: '/api/tasks',
  path: '/api/tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStatsRouteRoute = ApiStatsRouteRouteImport.update({
  id: '/api/stats',
  path: '/api/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCrawlRouteRoute = ApiCrawlRouteRouteImport.update({
  id: '/api/crawl',
  path: '/api/crawl',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiArticlesRouteRoute = ApiArticlesRouteRouteImport.update({
  id: '/api/articles',
  path: '/api/articles',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksIdPageRoute = TasksIdPageRouteImport.update({
  id: '/tasks/$id/',
  path: '/tasks/$id/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTasksClearFailedRouteRoute =
  ApiTasksClearFailedRouteRouteImport.update({
    id: '/clear-failed',
    path: '/clear-failed',
    getParentRoute: () => ApiTasksRouteRoute,
  } as any)
const ApiTasksIdRouteRoute = ApiTasksIdRouteRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiTasksRouteRoute,
} as any)
const ApiCronCheckCookieRouteRoute = ApiCronCheckCookieRouteRouteImport.update({
  id: '/api/cron/check-cookie',
  path: '/api/cron/check-cookie',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminFeedbackRouteRoute = ApiAdminFeedbackRouteRouteImport.update({
  id: '/api/admin/feedback',
  path: '/api/admin/feedback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminCookieStatusRouteRoute =
  ApiAdminCookieStatusRouteRouteImport.update({
    id: '/api/admin/cookie-status',
    path: '/api/admin/cookie-status',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAdminConfigRouteRoute = ApiAdminConfigRouteRouteImport.update({
  id: '/api/admin/config',
  path: '/api/admin/config',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminCheckCookieRouteRoute =
  ApiAdminCheckCookieRouteRouteImport.update({
    id: '/api/admin/check-cookie',
    path: '/api/admin/check-cookie',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAdminAuthRouteRoute = ApiAdminAuthRouteRouteImport.update({
  id: '/api/admin/auth',
  path: '/api/admin/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminArticlesRouteRoute = ApiAdminArticlesRouteRouteImport.update({
  id: '/api/admin/articles',
  path: '/api/admin/articles',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTasksIdFeedbackRouteRoute = ApiTasksIdFeedbackRouteRouteImport.update({
  id: '/feedback',
  path: '/feedback',
  getParentRoute: () => ApiTasksIdRouteRoute,
} as any)
const ApiAdminFeedbackIdRouteRoute = ApiAdminFeedbackIdRouteRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiAdminFeedbackRouteRoute,
} as any)
const ApiAdminArticlesIdRouteRoute = ApiAdminArticlesIdRouteRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiAdminArticlesRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof PageRoute
  '/api/articles': typeof ApiArticlesRouteRoute
  '/api/crawl': typeof ApiCrawlRouteRoute
  '/api/stats': typeof ApiStatsRouteRoute
  '/api/tasks': typeof ApiTasksRouteRouteWithChildren
  '/about/': typeof AboutPageRoute
  '/admin/': typeof AdminPageRoute
  '/stats/': typeof StatsPageRoute
  '/api/admin/articles': typeof ApiAdminArticlesRouteRouteWithChildren
  '/api/admin/auth': typeof ApiAdminAuthRouteRoute
  '/api/admin/check-cookie': typeof ApiAdminCheckCookieRouteRoute
  '/api/admin/config': typeof ApiAdminConfigRouteRoute
  '/api/admin/cookie-status': typeof ApiAdminCookieStatusRouteRoute
  '/api/admin/feedback': typeof ApiAdminFeedbackRouteRouteWithChildren
  '/api/cron/check-cookie': typeof ApiCronCheckCookieRouteRoute
  '/api/tasks/$id': typeof ApiTasksIdRouteRouteWithChildren
  '/api/tasks/clear-failed': typeof ApiTasksClearFailedRouteRoute
  '/tasks/$id/': typeof TasksIdPageRoute
  '/api/admin/articles/$id': typeof ApiAdminArticlesIdRouteRoute
  '/api/admin/feedback/$id': typeof ApiAdminFeedbackIdRouteRoute
  '/api/tasks/$id/feedback': typeof ApiTasksIdFeedbackRouteRoute
}
export interface FileRoutesByTo {
  '/': typeof PageRoute
  '/api/articles': typeof ApiArticlesRouteRoute
  '/api/crawl': typeof ApiCrawlRouteRoute
  '/api/stats': typeof ApiStatsRouteRoute
  '/api/tasks': typeof ApiTasksRouteRouteWithChildren
  '/about': typeof AboutPageRoute
  '/admin': typeof AdminPageRoute
  '/stats': typeof StatsPageRoute
  '/api/admin/articles': typeof ApiAdminArticlesRouteRouteWithChildren
  '/api/admin/auth': typeof ApiAdminAuthRouteRoute
  '/api/admin/check-cookie': typeof ApiAdminCheckCookieRouteRoute
  '/api/admin/config': typeof ApiAdminConfigRouteRoute
  '/api/admin/cookie-status': typeof ApiAdminCookieStatusRouteRoute
  '/api/admin/feedback': typeof ApiAdminFeedbackRouteRouteWithChildren
  '/api/cron/check-cookie': typeof ApiCronCheckCookieRouteRoute
  '/api/tasks/$id': typeof ApiTasksIdRouteRouteWithChildren
  '/api/tasks/clear-failed': typeof ApiTasksClearFailedRouteRoute
  '/tasks/$id': typeof TasksIdPageRoute
  '/api/admin/articles/$id': typeof ApiAdminArticlesIdRouteRoute
  '/api/admin/feedback/$id': typeof ApiAdminFeedbackIdRouteRoute
  '/api/tasks/$id/feedback': typeof ApiTasksIdFeedbackRouteRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof PageRoute
  '/api/articles': typeof ApiArticlesRouteRoute
  '/api/crawl': typeof ApiCrawlRouteRoute
  '/api/stats': typeof ApiStatsRouteRoute
  '/api/tasks': typeof ApiTasksRouteRouteWithChildren
  '/about/': typeof AboutPageRoute
  '/admin/': typeof AdminPageRoute
  '/stats/': typeof StatsPageRoute
  '/api/admin/articles': typeof ApiAdminArticlesRouteRouteWithChildren
  '/api/admin/auth': typeof ApiAdminAuthRouteRoute
  '/api/admin/check-cookie': typeof ApiAdminCheckCookieRouteRoute
  '/api/admin/config': typeof ApiAdminConfigRouteRoute
  '/api/admin/cookie-status': typeof ApiAdminCookieStatusRouteRoute
  '/api/admin/feedback': typeof ApiAdminFeedbackRouteRouteWithChildren
  '/api/cron/check-cookie': typeof ApiCronCheckCookieRouteRoute
  '/api/tasks/$id': typeof ApiTasksIdRouteRouteWithChildren
  '/api/tasks/clear-failed': typeof ApiTasksClearFailedRouteRoute
  '/tasks/$id/': typeof TasksIdPageRoute
  '/api/admin/articles/$id': typeof ApiAdminArticlesIdRouteRoute
  '/api/admin/feedback/$id': typeof ApiAdminFeedbackIdRouteRoute
  '/api/tasks/$id/feedback': typeof ApiTasksIdFeedbackRouteRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/articles'
    | '/api/crawl'
    | '/api/stats'
    | '/api/tasks'
    | '/about/'
    | '/admin/'
    | '/stats/'
    | '/api/admin/articles'
    | '/api/admin/auth'
    | '/api/admin/check-cookie'
    | '/api/admin/config'
    | '/api/admin/cookie-status'
    | '/api/admin/feedback'
    | '/api/cron/check-cookie'
    | '/api/tasks/$id'
    | '/api/tasks/clear-failed'
    | '/tasks/$id/'
    | '/api/admin/articles/$id'
    | '/api/admin/feedback/$id'
    | '/api/tasks/$id/feedback'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/articles'
    | '/api/crawl'
    | '/api/stats'
    | '/api/tasks'
    | '/about'
    | '/admin'
    | '/stats'
    | '/api/admin/articles'
    | '/api/admin/auth'
    | '/api/admin/check-cookie'
    | '/api/admin/config'
    | '/api/admin/cookie-status'
    | '/api/admin/feedback'
    | '/api/cron/check-cookie'
    | '/api/tasks/$id'
    | '/api/tasks/clear-failed'
    | '/tasks/$id'
    | '/api/admin/articles/$id'
    | '/api/admin/feedback/$id'
    | '/api/tasks/$id/feedback'
  id:
    | '__root__'
    | '/'
    | '/api/articles'
    | '/api/crawl'
    | '/api/stats'
    | '/api/tasks'
    | '/about/'
    | '/admin/'
    | '/stats/'
    | '/api/admin/articles'
    | '/api/admin/auth'
    | '/api/admin/check-cookie'
    | '/api/admin/config'
    | '/api/admin/cookie-status'
    | '/api/admin/feedback'
    | '/api/cron/check-cookie'
    | '/api/tasks/$id'
    | '/api/tasks/clear-failed'
    | '/tasks/$id/'
    | '/api/admin/articles/$id'
    | '/api/admin/feedback/$id'
    | '/api/tasks/$id/feedback'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  PageRoute: typeof PageRoute
  ApiArticlesRouteRoute: typeof ApiArticlesRouteRoute
  ApiCrawlRouteRoute: typeof ApiCrawlRouteRoute
  ApiStatsRouteRoute: typeof ApiStatsRouteRoute
  ApiTasksRouteRoute: typeof ApiTasksRouteRouteWithChildren
  AboutPageRoute: typeof AboutPageRoute
  AdminPageRoute: typeof AdminPageRoute
  StatsPageRoute: typeof StatsPageRoute
  ApiAdminArticlesRouteRoute: typeof ApiAdminArticlesRouteRouteWithChildren
  ApiAdminAuthRouteRoute: typeof ApiAdminAuthRouteRoute
  ApiAdminCheckCookieRouteRoute: typeof ApiAdminCheckCookieRouteRoute
  ApiAdminConfigRouteRoute: typeof ApiAdminConfigRouteRoute
  ApiAdminCookieStatusRouteRoute: typeof ApiAdminCookieStatusRouteRoute
  ApiAdminFeedbackRouteRoute: typeof ApiAdminFeedbackRouteRouteWithChildren
  ApiCronCheckCookieRouteRoute: typeof ApiCronCheckCookieRouteRoute
  TasksIdPageRoute: typeof TasksIdPageRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stats/': {
      id: '/stats/'
      path: '/stats'
      fullPath: '/stats/'
      preLoaderRoute: typeof StatsPageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminPageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about/': {
      id: '/about/'
      path: '/about'
      fullPath: '/about/'
      preLoaderRoute: typeof AboutPageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tasks': {
      id: '/api/tasks'
      path: '/api/tasks'
      fullPath: '/api/tasks'
      preLoaderRoute: typeof ApiTasksRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stats': {
      id: '/api/stats'
      path: '/api/stats'
      fullPath: '/api/stats'
      preLoaderRoute: typeof ApiStatsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/crawl': {
      id: '/api/crawl'
      path: '/api/crawl'
      fullPath: '/api/crawl'
      preLoaderRoute: typeof ApiCrawlRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/articles': {
      id: '/api/articles'
      path: '/api/articles'
      fullPath: '/api/articles'
      preLoaderRoute: typeof ApiArticlesRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks/$id/': {
      id: '/tasks/$id/'
      path: '/tasks/$id'
      fullPath: '/tasks/$id/'
      preLoaderRoute: typeof TasksIdPageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tasks/clear-failed': {
      id: '/api/tasks/clear-failed'
      path: '/clear-failed'
      fullPath: '/api/tasks/clear-failed'
      preLoaderRoute: typeof ApiTasksClearFailedRouteRouteImport
      parentRoute: typeof ApiTasksRouteRoute
    }
    '/api/tasks/$id': {
      id: '/api/tasks/$id'
      path: '/$id'
      fullPath: '/api/tasks/$id'
      preLoaderRoute: typeof ApiTasksIdRouteRouteImport
      parentRoute: typeof ApiTasksRouteRoute
    }
    '/api/cron/check-cookie': {
      id: '/api/cron/check-cookie'
      path: '/api/cron/check-cookie'
      fullPath: '/api/cron/check-cookie'
      preLoaderRoute: typeof ApiCronCheckCookieRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/feedback': {
      id: '/api/admin/feedback'
      path: '/api/admin/feedback'
      fullPath: '/api/admin/feedback'
      preLoaderRoute: typeof ApiAdminFeedbackRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/cookie-status': {
      id: '/api/admin/cookie-status'
      path: '/api/admin/cookie-status'
      fullPath: '/api/admin/cookie-status'
      preLoaderRoute: typeof ApiAdminCookieStatusRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/config': {
      id: '/api/admin/config'
      path: '/api/admin/config'
      fullPath: '/api/admin/config'
      preLoaderRoute: typeof ApiAdminConfigRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/check-cookie': {
      id: '/api/admin/check-cookie'
      path: '/api/admin/check-cookie'
      fullPath: '/api/admin/check-cookie'
      preLoaderRoute: typeof ApiAdminCheckCookieRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/auth': {
      id: '/api/admin/auth'
      path: '/api/admin/auth'
      fullPath: '/api/admin/auth'
      preLoaderRoute: typeof ApiAdminAuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/articles': {
      id: '/api/admin/articles'
      path: '/api/admin/articles'
      fullPath: '/api/admin/articles'
      preLoaderRoute: typeof ApiAdminArticlesRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tasks/$id/feedback': {
      id: '/api/tasks/$id/feedback'
      path: '/feedback'
      fullPath: '/api/tasks/$id/feedback'
      preLoaderRoute: typeof ApiTasksIdFeedbackRouteRouteImport
      parentRoute: typeof ApiTasksIdRouteRoute
    }
    '/api/admin/feedback/$id': {
      id: '/api/admin/feedback/$id'
      path: '/$id'
      fullPath: '/api/admin/feedback/$id'
      preLoaderRoute: typeof ApiAdminFeedbackIdRouteRouteImport
      parentRoute: typeof ApiAdminFeedbackRouteRoute
    }
    '/api/admin/articles/$id': {
      id: '/api/admin/articles/$id'
      path: '/$id'
      fullPath: '/api/admin/articles/$id'
      preLoaderRoute: typeof ApiAdminArticlesIdRouteRouteImport
      parentRoute: typeof ApiAdminArticlesRouteRoute
    }
  }
}

interface ApiTasksIdRouteRouteChildren {
  ApiTasksIdFeedbackRouteRoute: typeof ApiTasksIdFeedbackRouteRoute
}

const ApiTasksIdRouteRouteChildren: ApiTasksIdRouteRouteChildren = {
  ApiTasksIdFeedbackRouteRoute: ApiTasksIdFeedbackRouteRoute,
}

const ApiTasksIdRouteRouteWithChildren = ApiTasksIdRouteRoute._addFileChildren(
  ApiTasksIdRouteRouteChildren,
)

interface ApiTasksRouteRouteChildren {
  ApiTasksIdRouteRoute: typeof ApiTasksIdRouteRouteWithChildren
  ApiTasksClearFailedRouteRoute: typeof ApiTasksClearFailedRouteRoute
}

const ApiTasksRouteRouteChildren: ApiTasksRouteRouteChildren = {
  ApiTasksIdRouteRoute: ApiTasksIdRouteRouteWithChildren,
  ApiTasksClearFailedRouteRoute: ApiTasksClearFailedRouteRoute,
}

const ApiTasksRouteRouteWithChildren = ApiTasksRouteRoute._addFileChildren(
  ApiTasksRouteRouteChildren,
)

interface ApiAdminArticlesRouteRouteChildren {
  ApiAdminArticlesIdRouteRoute: typeof ApiAdminArticlesIdRouteRoute
}

const ApiAdminArticlesRouteRouteChildren: ApiAdminArticlesRouteRouteChildren = {
  ApiAdminArticlesIdRouteRoute: ApiAdminArticlesIdRouteRoute,
}

const ApiAdminArticlesRouteRouteWithChildren =
  ApiAdminArticlesRouteRoute._addFileChildren(
    ApiAdminArticlesRouteRouteChildren,
  )

interface ApiAdminFeedbackRouteRouteChildren {
  ApiAdminFeedbackIdRouteRoute: typeof ApiAdminFeedbackIdRouteRoute
}

const ApiAdminFeedbackRouteRouteChildren: ApiAdminFeedbackRouteRouteChildren = {
  ApiAdminFeedbackIdRouteRoute: ApiAdminFeedbackIdRouteRoute,
}

const ApiAdminFeedbackRouteRouteWithChildren =
  ApiAdminFeedbackRouteRoute._addFileChildren(
    ApiAdminFeedbackRouteRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  PageRoute: PageRoute,
  ApiArticlesRouteRoute: ApiArticlesRouteRoute,
  ApiCrawlRouteRoute: ApiCrawlRouteRoute,
  ApiStatsRouteRoute: ApiStatsRouteRoute,
  ApiTasksRouteRoute: ApiTasksRouteRouteWithChildren,
  AboutPageRoute: AboutPageRoute,
  AdminPageRoute: AdminPageRoute,
  StatsPageRoute: StatsPageRoute,
  ApiAdminArticlesRouteRoute: ApiAdminArticlesRouteRouteWithChildren,
  ApiAdminAuthRouteRoute: ApiAdminAuthRouteRoute,
  ApiAdminCheckCookieRouteRoute: ApiAdminCheckCookieRouteRoute,
  ApiAdminConfigRouteRoute: ApiAdminConfigRouteRoute,
  ApiAdminCookieStatusRouteRoute: ApiAdminCookieStatusRouteRoute,
  ApiAdminFeedbackRouteRoute: ApiAdminFeedbackRouteRouteWithChildren,
  ApiCronCheckCookieRouteRoute: ApiCronCheckCookieRouteRoute,
  TasksIdPageRoute: TasksIdPageRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
